version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokeguesser
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - poke-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_pokeguesser
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - poke-net

  backend:
    image: python:3.11-slim
    container_name: backend
    volumes:
      - ../scripts:/app/scripts
      - ../backend:/app/backend
    working_dir: /app
    depends_on:
      - db
      - rabbitmq
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/pokeguesser
      RABBITMQ_HOST: rabbitmq
    command: bash -c "pip install --no-cache-dir -r backend/requirements.txt && tail -f /dev/null"
    networks:
      - poke-net

networks:
  poke-net:
    driver: bridge
